export enum clientEnum {
  GIC = 'gic',
  UOB = 'uob',
  JULIUS_BAR = 'julius_bar',
  CANON = 'canon',
  SSA = 'ssa',
  IMO = 'imo',
  MPA = 'mpa',
  PA = 'pa',
  SRI = 'sri',
  SUNTEC = 'suntec',
  TSL = 'tsl',
  TYME = 'tyme',
  DXD = 'dxd',
  MTJ = 'mtj',
  GOMU = 'gomu',
  IIX = 'iix',
  SPIKING = 'spiking',
  MOH = 'moh',
}
