import {
  AlignCenter,
  ArrowBigRight,
  ArrowRight,
  ArrowRightCircle,
  Award,
  BarChart,
  BarChart2,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  Car,
  Check,
  CheckCheck,
  CheckCircle,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Code2,
  Cog,
  Coins,
  Compass,
  Copy,
  CreditCard,
  Database,
  Dna,
  DollarSign,
  Eye,
  FileCheck,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  FlaskRound,
  FolderOpen,
  Gavel,
  Gem,
  GitBranch,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Hospital,
  Image,
  Infinity,
  Lamp,
  Landmark,
  Laptop,
  Laptop2,
  Layers,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Lock,
  LucideIcon,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Microscope,
  Minimize2,
  Monitor,
  Mouse,
  Move,
  Navigation,
  Network,
  Paintbrush,
  Palette,
  PenTool,
  Pencil,
  PieChart,
  Plane,
  Plug,
  Puzzle,
  Radio,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Route,
  Ruler,
  Scale,
  Scroll,
  Search,
  SearchCheck,
  Server,
  Settings,
  Settings2,
  Shapes,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Smile,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Target,
  Timer,
  Trophy,
  Truck,
  User,
  UserCheck,
  UserCircle,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Watch,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react'

// Mapping from FontAwesome icon classes to Lucide React components
export const faToLucideMap: Record<string, LucideIcon> = {
  'fa-align-center': AlignCenter,
  'fa-analytics': BarChart2,
  'fa-arrow-circle-right': ArrowRightCircle,
  'fa-arrow-right': ArrowRight,
  'fa-award': Award,
  'fa-balance-scale': Scale,
  'fa-bar-chart': BarChart,
  'fa-bell': Bell,
  'fa-bolt': Zap,
  'fa-book': BookOpen,
  'fa-brain': Brain,
  'fa-briefcase': Briefcase,
  'fa-broadcast-tower': Radio,
  'fa-bug': Bug,
  'fa-building': Building,
  'fa-bullhorn': Megaphone,
  'fa-bullseye': Target,
  'fa-business-time': Briefcase,
  'fa-calendar-alt': Calendar,
  'fa-car': Car,
  'fa-certificate': Award,
  'fa-chalkboard-teacher': GraduationCap,
  'fa-chart-area': BarChart3,
  'fa-chart-bar': BarChart,
  'fa-chart-line': LineChart,
  'fa-chart-mixed': BarChart2,
  'fa-chart-network': Network,
  'fa-chart-pie': PieChart,
  'fa-check': Check,
  'fa-check-circle': CheckCircle,
  'fa-check-double': CheckCheck,
  'fa-circle-bolt': Zap,
  'fa-clipboard-check': ClipboardCheck,
  'fa-clipboard-list': ClipboardList,
  'fa-clock': Clock,
  'fa-clone': Copy,
  'fa-cloud': Cloud,
  'fa-cloud-binary': Cloud,
  'fa-cloud-download-alt': CloudDownload,
  'fa-cloud-upload-alt': CloudUpload,
  'fa-code': Code,
  'fa-code-branch': GitBranch,
  'fa-cog': Cog,
  'fa-cogs': Settings,
  'fa-coins': Coins,
  'fa-comment': MessageCircle,
  'fa-comment-alt': MessageSquare,
  'fa-comments': MessageSquare,
  'fa-comments-dollar': MessageSquare,
  'fa-compass': Compass,
  'fa-compress': Minimize2,
  'fa-credit-card': CreditCard,
  'fa-cube': Box,
  'fa-cubes': Boxes,
  'fa-database': Database,
  'fa-desktop': Monitor,
  'fa-dice-d': Shapes,
  'fa-digital-tachograph': Timer,
  'fa-directions': Navigation,
  'fa-dna': Dna,
  'fa-dollar-sign': DollarSign,
  'fa-drafting-compass': Compass,
  'fa-envelope': Mail,
  'fa-exchange-alt': RefreshCw,
  'fa-exclamation-triangle': Flame,
  'fa-expand': Maximize,
  'fa-expand-alt': Maximize2,
  'fa-expand-arrows-alt': Move,
  'fa-eye': Eye,
  'fa-file-alt': FileText,
  'fa-file-contract': FileCheck,
  'fa-file-invoice-dollar': FileText,
  'fa-file-medical': FileText,
  'fa-flag-checkered': Flag,
  'fa-flask': FlaskRound,
  'fa-flask-vial': FlaskConical,
  'fa-folder-open': FolderOpen,
  'fa-gavel': Gavel,
  'fa-gears': Settings2,
  'fa-gem': Gem,
  'fa-gingerbread-man': User,
  'fa-globe': Globe,
  'fa-graduation-cap': GraduationCap,
  'fa-guitar': Guitar,
  'fa-hammer': Hammer,
  'fa-hand-holding-seedling': Sprout,
  'fa-hand-holding-usd': DollarSign,
  'fa-hands-helping': Users,
  'fa-handshake': Handshake,
  'fa-headset': Headphones,
  'fa-heart': Heart,
  'fa-home': Home,
  'fa-hospitals': Hospital,
  'fa-images': Image,
  'fa-industry-windows': Building2,
  'fa-infinity': Infinity,
  'fa-kit-medical': Stethoscope,
  'fa-lamp-street': Lamp,
  'fa-landmark-flag': Landmark,
  'fa-laptop': Laptop,
  'fa-laptop-code': Laptop2,
  'fa-laptop-medical': Laptop,
  'fa-layer-group': Layers,
  'fa-life-ring': LifeBuoy,
  'fa-lightbulb': Lightbulb,
  'fa-line-chart': LineChart,
  'fa-link': Link,
  'fa-lock': Lock,
  'fa-magic': Zap,
  'fa-map': Map,
  'fa-map-marked-alt': MapPin,
  'fa-map-signs': Navigation,
  'fa-medkit': Stethoscope,
  'fa-microscope': Microscope,
  'fa-mobile': Laptop,
  'fa-mobile-alt': Laptop,
  'fa-money-bill-alt': DollarSign,
  'fa-money-bill-trend-up': LineChart,
  'fa-money-bill-wave': DollarSign,
  'fa-money-check-alt': CreditCard,
  'fa-mouse-pointer': Mouse,
  'fa-mug-hot': Flame,
  'fa-network-wired': Network,
  'fa-notes-medical': ClipboardList,
  'fa-object-group': Shapes,
  'fa-paint-brush': Paintbrush,
  'fa-palette': Palette,
  'fa-pen-nib': PenTool,
  'fa-pencil-ruler': Pencil,
  'fa-people-arrows': Users,
  'fa-people-carry': Users,
  'fa-people-group': Users,
  'fa-plane-departure': Plane,
  'fa-plug': Plug,
  'fa-project-diagram': Workflow,
  'fa-puzzle-piece': Puzzle,
  'fa-question-circle': HelpCircle,
  'fa-react': Code2,
  'fa-refresh': RefreshCcw,
  'fa-road': Route,
  'fa-robot': Cog,
  'fa-rocket': Rocket,
  'fa-route': Route,
  'fa-ruler-combined': Ruler,
  'fa-scale-balanced': Scale,
  'fa-scroll': Scroll,
  'fa-search': Search,
  'fa-search-dollar': SearchCheck,
  'fa-search-plus': Search,
  'fa-seedling': Sprout,
  'fa-server': Server,
  'fa-shapes': Shapes,
  'fa-share-alt': Share2,
  'fa-shield-alt': Shield,
  'fa-ship': Ship,
  'fa-shopping-cart': ShoppingCart,
  'fa-sitemap': Workflow,
  'fa-smile': Smile,
  'fa-solar-panel': Sun,
  'fa-stethoscope': Stethoscope,
  'fa-store': Store,
  'fa-sync': RefreshCw,
  'fa-sync-alt': RefreshCcw,
  'fa-table-tennis': Target,
  'fa-tachometer-alt': Timer,
  'fa-tasks': ClipboardCheck,
  'fa-thin': Shapes,
  'fa-tools': Wrench,
  'fa-trophy': Trophy,
  'fa-truck-moving': Truck,
  'fa-universal-access': Users,
  'fa-user': User,
  'fa-user-check': UserCheck,
  'fa-user-circle': UserCircle,
  'fa-user-cog': UserCog,
  'fa-user-friends': Users,
  'fa-user-plus': UserPlus,
  'fa-user-secret': User,
  'fa-user-shield': ShieldCheck,
  'fa-user-tag': User,
  'fa-user-tie': User,
  'fa-users': Users,
  'fa-users-cog': Settings,
  'fa-wallet': Wallet,
  'fa-warehouse': Warehouse,
  'fa-watch': Watch,
  'fa-wrench': Wrench,
}

// Extract just the icon name from full FA class string (e.g., "fa-light fa-rocket" -> "fa-rocket")
export const extractFaIconName = (faClass: string): string | null => {
  const match = faClass.match(/fa-[a-z][a-z-]+(?!-)/g)
  if (!match) return null
  // Filter out style prefixes like fa-light, fa-solid, fa-regular, fa-thin, fa-duotone
  const iconName = match.find(
    (name) =>
      !['fa-light', 'fa-solid', 'fa-regular', 'fa-thin', 'fa-duotone', 'fa-brands'].includes(name)
  )
  return iconName || null
}

// Get Lucide icon component from FA class string
export const getLucideIcon = (faClass: string): LucideIcon | null => {
  const iconName = extractFaIconName(faClass)
  if (!iconName) return null
  return faToLucideMap[iconName] || null
}
